_BASE_: ./eval.yaml

MODEL:
  MASK_FORMER:
    TEST:
      PANOPTIC_ON: False
      INSTANCE_ON: False

DATASETS:
  TEST: ("openvocab_pascal_ctx459_sem_seg_val",)

OUTPUT_DIR: ./training/maftp-large_warmup/eval/pc459